# Generated by Django 5.2.11 on 2026-02-16 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('css', models.TextField(blank=True, help_text='CSS personnalisé pour cette fiche')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche personnage',
                'verbose_name_plural': 'Fiches personnages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionAutres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, verbose_name='Autres informations')),
                ('css', models.TextField(blank=True, help_text='CSS personnalisé pour la section Autres')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autres', to='fiches.fiche')),
            ],
            options={
                'verbose_name': 'Section Autres',
                'verbose_name_plural': 'Sections Autres',
            },
        ),
        migrations.CreateModel(
            name='SectionCaractere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, verbose_name='Caractère et personnalité')),
                ('css', models.TextField(blank=True, help_text='CSS personnalisé pour la section Caractère')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caractere', to='fiches.fiche')),
            ],
            options={
                'verbose_name': 'Section Caractère',
                'verbose_name_plural': 'Sections Caractère',
            },
        ),
        migrations.CreateModel(
            name='SectionHistoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, verbose_name='Histoire du personnage')),
                ('css', models.TextField(blank=True, help_text='CSS personnalisé pour la section Histoire')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='histoire', to='fiches.fiche')),
            ],
            options={
                'verbose_name': 'Section Histoire',
                'verbose_name_plural': 'Sections Histoire',
            },
        ),
        migrations.CreateModel(
            name='SectionPhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description physique')),
                ('corpulence', models.CharField(blank=True, max_length=200, verbose_name='Corpulence')),
                ('traits_particuliers', models.TextField(blank=True, verbose_name='Traits particuliers')),
                ('poids', models.CharField(blank=True, max_length=100, verbose_name='Poids')),
                ('taille', models.CharField(blank=True, max_length=100, verbose_name='Taille')),
                ('genre', models.CharField(blank=True, max_length=200, verbose_name='Genre')),
                ('date_naissance_rp', models.DateField(blank=True, help_text='Date de naissance dans le temps du RP', null=True, verbose_name='Date de naissance (RP)')),
                ('age_manuel', models.CharField(blank=True, help_text='Laissez vide pour calcul automatique basé sur la date de naissance RP', max_length=100, verbose_name='Âge (manuel)')),
                ('autres_infos', models.TextField(blank=True, verbose_name='Autres informations physiques')),
                ('css', models.TextField(blank=True, help_text='CSS personnalisé pour la section Physique')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physique', to='fiches.fiche')),
            ],
            options={
                'verbose_name': 'Section Physique',
                'verbose_name_plural': 'Sections Physique',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_server_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.URLField(blank=True, null=True)),
                ('css', models.TextField(blank=True, help_text='CSS global du serveur')),
                ('date_rp_reference', models.DateField(help_text='Date à laquelle correspond la date réelle de référence (ex: 1er janvier 2027)', verbose_name='Date RP de référence')),
                ('date_reelle_reference', models.DateField(help_text='Date réelle correspondant à la date RP de référence', verbose_name='Date réelle de référence')),
                ('ratio_temps', models.DecimalField(decimal_places=2, default=1.0, help_text='Ex: 2.0 = 2 jours RP pour 1 jour réel | 0.5 = 1 jour RP pour 2 jours réels', max_digits=5, verbose_name='Ratio temps (jours RP / jour réel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, help_text='Utilisateurs pouvant gérer ce serveur', related_name='admin_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serveur Discord',
                'verbose_name_plural': 'Serveurs Discord',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fiche',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='fiches.server'),
        ),
    ]
